# Generated by Django 5.2.3 on 2025-07-13 16:09

# users/migrations/000X_create_blog_groups.py
from django.db import migrations


def create_groups(apps, _):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    perms = Permission.objects.filter(
        content_type__app_label="posts",
        codename__in=["add_post", "change_post", "delete_post", "view_post"],
    )

    role_perms = {
        "Admin": perms,
        "Editor": perms,  # same perms, different behaviour later
        "Writer": perms,
    }

    for role, perms_qs in role_perms.items():
        group, _ = Group.objects.get_or_create(name=role)
        group.permissions.set(perms_qs)


def drop_groups(apps, _):
    apps.get_model("auth", "Group").objects.filter(
        name__in=["Admin", "Editor", "Writer"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_full_name"),
    ]
    operations = [migrations.RunPython(create_groups, drop_groups)]
